name: 'SNWFLKABNB'
version: '1.0'
config-version: 2

profile: 'SNWFLKABNB'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  SNWFLKABNB:
    raw_sources:
      +schema: raw
      +materialized: view
    staging:
      +schema: staging
      +materialized: view
    dimensions:
      +schema: dimensions
      +materialized: table
