SNWFLKABNB:
  outputs:
    dev:
      account: abcdefg-cr86200
      database: AIRBNB
      password: password
      role: ACCOUNTADMIN
      schema: AIRBNB.RAW
      threads: 4
      type: snowflake
      user: Dilip1100
      warehouse: COMPUTE_WH
  target: dev
snowflake:
  outputs:
    dev:
      account: https://app.snowflake.com/abcdefg-cr86200
      client_session_keep_alive: true
      database: AIRBNB
      password: password
      role: ACCOUNTADMIN
      type: snowflake
      user: Dilip1100
      warehouse: COMPUTE_WH
